# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Xeol < Formula
  desc "An EOL package scanner for container images, systems, and SBOMs"
  homepage "https://github.com/xeol-io/xeol"
  version "0.2.7"
  license "Apache License 2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/xeol-io/xeol/releases/download/v0.2.7/xeol_0.2.7_darwin_arm64.tar.gz"
      sha256 "197ae3b762618c78af62405d448286c474f4b680e923228408c89e7fb73db48e"

      def install
        bin.install "xeol"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/xeol-io/xeol/releases/download/v0.2.7/xeol_0.2.7_darwin_amd64.tar.gz"
      sha256 "a900e31794123f94ec220df23edb6a423ec3997987425bcbd44f56392fab344b"

      def install
        bin.install "xeol"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/xeol-io/xeol/releases/download/v0.2.7/xeol_0.2.7_linux_arm64.tar.gz"
      sha256 "a9f8215195f2726208f101781b5948dfbe5fc4d5ac71f79bd00838586651d32b"

      def install
        bin.install "xeol"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/xeol-io/xeol/releases/download/v0.2.7/xeol_0.2.7_linux_amd64.tar.gz"
      sha256 "a02392f667342016945fe1d529ccc8d906b9029db332ff75a6624a98612ff9cb"

      def install
        bin.install "xeol"
      end
    end
  end
end
